#!/usr/bin/env php
<?php

if(file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('JumpGate Server Commander', '1.2');
$app->add(new JumpGate\Server\Console\NewSiteCommand);

$app->run();
